version: "3.8"
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stock_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis_cache
    ports:
      - "6379:6379"

  celery_worker:
    build: ../
    container_name: celery_worker
    command: celery -A tasks.tasks worker --loglevel=info
    depends_on:
      - redis
      - postgres

  streamlit:
    build: ../
    container_name: streamlit_app
    command: streamlit run app.py
    ports:
      - "8501:8501"
    depends_on:
      - postgres

volumes:
  pgdata:
